	$(function(){
		/* Incluimos un método para validar el campo nombre */
		jQuery.validator.addMethod("texto", function(value, element) {
			return this.optional(element) || /^[a-záéóóúàèìòùäëïöüñ\s]+$/i.test(value);
		}); 
	/* Capturar el click del botón */
	$("#btn").on("click", function(){
		/* Validar el formulario */
		$("#formulario").validate({
		 rules: /* Accedemos a los campos a través de su nombre: email, nombre, edad */
		 {
			 //email: {required: true, email: true, minlength: 5, maxlength: 80},
			 historia_laboral: {required: true},
			 anosenempresa: {digits: true, minlength: 1, min: 1, max:99},
			 dependencia: {maxlength: 50},
			 cargo_historia: {maxlength: 50},
			 descripcioncargo: {maxlength: 100},
			 
			 actividades: {maxlength: 50},
			 acciones: {maxlength: 50},

			 exposicion_riesgo: {required: true},
			 empresa1_riesgo: {maxlength: 20, texto: true},
			 riesgo_cargo1:{maxlength: 30, texto: true},
			 riesgo_epp1: {maxlength: 30},
				empresa2_riesgo: {maxlength: 20, texto: true},
			 riesgo_cargo2:{maxlength: 30, texto: true},
			 riesgo_epp2: {maxlength: 30},
				empresa3_riesgo: {maxlength: 20, texto: true},
			 riesgo_cargo3:{maxlength: 30, texto: true},
			 riesgo_epp3: {maxlength: 30},
			 empresa4_riesgo: {maxlength: 20, texto: true},
			 riesgo_cargo4:{maxlength: 30, texto: true},
			 riesgo_epp4: {maxlength: 30},
			 empresa5_riesgo: {maxlength: 20, texto: true},
			 riesgo_cargo5:{maxlength: 30, texto: true},
			 riesgo_epp5: {maxlength: 30},               
			 //nombreempresa: {required: true, minlength: 2, maxlength: 50},

			 ant_infancia: {required: true},
			 ant_cardiaca: {required: true},
			 ant_trauma: {required: true},
			 ant_transmision_sexual: {required: true},
			 ant_vacunas: {required: true},
			 ant_toxicos: {required: true},

			 ant_hipertension: {required: true},
			 ant_piel: {required: true},
			 ant_renal: {required: true},
			 ant_peptica: {required: true},
			 ant_mental: {required: true},

			 ant_alergias: {required: true},
			 ant_hernias: {required: true},
			 ant_oido_nariz_laringe: {required: true},
			 ant_visuales: {required: true},
			 ant_hematicos: {required: true},

			 ant_cirugias: {required: true},
			 ant_carpo: {required: true},
			 ant_vascular: {required: true},
			 ant_varicocele: {required: true},
			 ant_hepatica: {required: true},
				ant_osteomuscular: {required: true},

			 ant_hospital: {required: true},
			 ant_quervein: {required: true},
			 ant_lumbalgias: {required: true},
			 ant_cancer: {required: true},
			 ant_fracturas: {required: true},
			 ant_dislipidemias: {required: true},

			 ant_observacion: {required: true, maxlength: 200},

			 ant_familiar_descripcion: {maxlength: 150},
			 ant_personal_descripcion: {maxlength: 150},

			 gin_menarquia: {digits: true, minlength: 1, min: 1, max:99},
			 gin_metodo: {maxlength: 50},


			 usoproteccion_p: {required: true},

			 ele_proteccion_cargo: {required: true},
			 proteccion_actual: {required: true},
			 casco: {required: true},
			 guantes: {required: true},
			 botas: {required: true},
			 gafas: {required: true},
			 tapabocas: {required: true},
			 overol: {required: true},
			 p_auditivos: {required: true},
			 p_respiratorios: {required: true},
			 p_otros: {maxlength: 60},
			 solo_ad: {maxlength: 60},
			 p_adecuada: {required: true},
			 todoadecuado: {required: true},

			 accidentestrabajo: {required: true},
			 empresaaccidente: {maxlength: 20, texto: true},
			 causaaccidente: {maxlength: 30},
			 parteafectadaaccidente: {maxlength: 30},
			 empresaaccidente2: {maxlength: 20, texto: true},
			 causaaccidente2: {maxlength: 30},
			 parteafectadaaccidente2: {maxlength: 30},
			 empresaaccidente3: {maxlength: 20, texto: true},
			 causaaccidente3: {maxlength: 30},
			 parteafectadaaccidente3: {maxlength: 30},
				empresaaccidente4: {maxlength: 20, texto: true},
			 causaaccidente4: {maxlength: 30},
			 parteafectadaaccidente4: {maxlength: 30},
			 empresaaccidente5: {maxlength: 20, texto: true},
			 causaaccidente5: {maxlength: 30},
			 parteafectadaaccidente5: {maxlength: 30},

			 enfermedad_p:{required: true},
			 enfermedad:{maxlength: 60},
			 empresaenfermedad:{maxlength:30, texto: true},
			 diagnosticoenfermedad: {maxlength: 150},

			 enfermedad2:{maxlength: 60},
			 empresaenfermedad2:{maxlength:30, texto: true},
			 diagnosticoenfermedad2: {maxlength: 150},

			 enfermedad3:{maxlength: 60},
			 empresaenfermedad3:{maxlength:30, texto: true},
			 diagnosticoenfermedad3: {maxlength: 150},

			 enfermedad4:{maxlength: 60},
			 empresaenfermedad4:{maxlength:30, texto: true},
			 diagnosticoenfermedad4: {maxlength: 150},  

			 enfermedad5:{maxlength: 60},
			 empresaenfermedad5:{maxlength:30, texto: true},
			 diagnosticoenfermedad5: {maxlength: 150},

			 deporte: {required: true},
			 sedentario: {required: true},
			 depor_cardiopulmonar: {required: true},
			 cual_deporte: {maxlength: 60},

			 fuma: {required: true}, 
			 fumador: {required: true}, 
			 anosfumador: {digits: true, minlength: 1, min: 1, max:99},
			 exfumador: {required: true},  
			 anosexfumador: {digits: true, minlength: 1, min: 1, max:99}, 
			 cantidad_cigarrillos_dia: {digits: true, minlength: 1, min: 1, max:70}, 
			 tomahab: {required: true},
			 anoshab_beber: {digits: true, minlength: 1, min: 1, max:99},
			 frec_beber: {required: true}, 
			 problemasbebidas: {required: true},
			 cuales_bebidas: {maxlength: 50},
			 exbebedor: {required: true},
			 exbebedor_anos: {digits: true, minlength: 1, min: 1, max:99}, 
			 otroshabitos: {required: true},
			 nombre_otrohabito: {maxlength: 50},
			 medic_regularmente: {required: true},
				nombre_medicamento: {maxlength: 50},

				cirugiaseps: {required: true},
				cuales_cirugias: {maxlength: 60},
				pend_tratamiento: {required: true},
				cuales_tratamientos: {maxlength: 60},
				incapacidadultimosmeses: {required: true},
				motivo_incapacidad: {maxlength: 80}, 
				mano_habil: {required: true},
				cicatrices: {required: true},
				tatuajes: {required: true},
				perimetro_abdominal: {required: true},
				perimetro_toraxico: {required: true},
				otras_mediciones: {maxlength: 120},
				tensionarterial: {required: true},
				frecuenciacardiaca: {required: true},
				frecuenciarespiratoria: {required: true},
				talla: {required: true},
				peso: {required: true},
				pesodiagnostico: {required: true},
				riesgos_suministrado: {required: true},
				suministrado_otro: {maxlength: 50},
			 //botas: {required: true},
		 },

		 messages: /* Accedemos a los campos a través de su nombre: email, nombre, edad */
		 {
			 historia_laboral: {required: 'Selecionar una opcion'},
				anosenempresa: {digits: 'Sólo dígitos', minlength: 'El mínimo permitido son 1 caracteres', maxlength: 'El máximo permitido son 2 caracteres', min: 'Digite un año mayor o igual a 1', max:'Digite un año menor o igual a 99'},
				dependencia: {maxlength: 'El máximo permitido son 50 caracteres'},
			 cargo_historia: {maxlength: 'El máximo permitido son 50 caracteres'},
			 descripcioncargo: {maxlength: 'El máximo permitido son 100 caracteres'},
			 
			 actividades: {maxlength: 'El máximo permitido son 50 caracteres'},
			 acciones: {maxlength: 'El máximo permitido son 50 caracteres'},

			 exposicion_riesgo: {required: 'Selecionar una opcion'},
				empresa1_riesgo: {maxlength: 'El máximo permitido son 20 caracteres', texto: 'Ingrese solo texto'},
			 riesgo_cargo1:{maxlength: 'El máximo permitido son 30 caracteres', texto: 'Ingrese solo texto'},
			 riesgo_epp1: {maxlength: 'El máximo permitido son 30 caracteres'},
				empresa2_riesgo: {maxlength: 'El máximo permitido son 20 caracteres', texto: 'Ingrese solo texto'},
			 riesgo_cargo2:{maxlength: 'El máximo permitido son 30 caracteres', texto: 'Ingrese solo texto'},
			 riesgo_epp2: {maxlength: 'El máximo permitido son 30 caracteres'},
				empresa3_riesgo: {maxlength: 'El máximo permitido son 20 caracteres', texto: 'Ingrese solo texto'},
			 riesgo_cargo3:{maxlength: 'El máximo permitido son 30 caracteres', texto: 'Ingrese solo texto'},
			 riesgo_epp3: {maxlength: 'El máximo permitido son 30 caracteres'},
			 empresa4_riesgo: {maxlength: 'El máximo permitido son 20 caracteres', texto: 'Ingrese solo texto'},
			 riesgo_cargo4:{maxlength: 'El máximo permitido son 30 caracteres', texto: 'Ingrese solo texto'},
			 riesgo_epp4: {maxlength: 'El máximo permitido son 30 caracteres'},
			 empresa5_riesgo: {maxlength: 'El máximo permitido son 20 caracteres', texto: 'Ingrese solo texto'},
			 riesgo_cargo5:{maxlength: 'El máximo permitido son 30 caracteres', texto: 'Ingrese solo texto'},
			 riesgo_epp5: {maxlength: 'El máximo permitido son 30 caracteres'},

			 ant_infancia: {required: 'Seleccione'},
			 ant_cardiaca: {required: 'Seleccione'},
			 ant_trauma: {required: 'Seleccione'},
			 ant_transmision_sexual: {required: 'Seleccione'},
			 ant_vacunas: {required: 'Seleccione'},
			 ant_toxicos: {required: 'Seleccione'},

			 ant_hipertension: {required: 'Seleccione'},
			 ant_piel: {required: 'Seleccione'},
			 ant_renal: {required: 'Seleccione'},
			 ant_peptica: {required: 'Seleccione'},
			 ant_mental: {required: 'Seleccione'},

			 ant_alergias: {required: 'Seleccione'},
			 ant_hernias: {required: 'Seleccione'},
			 ant_oido_nariz_laringe: {required: 'Seleccione'},
			 ant_visuales: {required: 'Seleccione'},
			 ant_hematicos: {required: 'Seleccione'},

			 ant_cirugias: {required: 'Seleccione'},
			 ant_carpo: {required: 'Seleccione'},
			 ant_vascular: {required: 'Seleccione'},
			 ant_varicocele: {required: 'Seleccione'},
			 ant_hepatica: {required: 'Seleccione'},
				ant_osteomuscular: {required: 'Seleccione'},

			 ant_hospital: {required: 'Seleccione'},
			 ant_quervein: {required: 'Seleccione'},
			 ant_lumbalgias: {required: 'Seleccione'},
			 ant_cancer: {required: 'Seleccione'},
			 ant_fracturas: {required: 'Seleccione'},
			 ant_dislipidemias: {required: 'Seleccione'},

			 ant_observacion: {required: 'Este campo es requerido', maxlength: 'El máximo permitido son 200 caracteres'},

			 ant_familiar_descripcion: { maxlength: 'El máximo permitido son 150 caracteres'},
			 ant_personal_descripcion: {maxlength: 'El máximo permitido son 150 caracteres'},

			 gin_menarquia: {digits: 'Sólo dígitos', minlength: 'El mínimo permitido son 1 caracteres', maxlength: 'El máximo permitido son 2 caracteres', min: 'Digite un año mayor o igual a 1', max:'Digite un año menor o igual a 99'},

			 gin_metodo: {maxlength: 'El máximo permitido son 50 caracteres'},

			 usoproteccion_p: {required: 'Selecionar una opcion'},
			 ele_proteccion_cargo: {required: 'Seleccione'},
			 proteccion_actual: {required: 'Seleccione'},
			 casco: {required: 'Seleccione'},
			 guantes: {required: 'Seleccione'},
			 botas: {required: 'Seleccione'},
			 gafas: {required: 'Seleccione'},
			 tapabocas: {required: 'Seleccione'},
			 overol: {required: 'Seleccione'},
			 p_auditivos: {required: 'Seleccione'},
			 p_respiratorios: {required: 'Seleccione'},
			 p_otros: {maxlength: 'El máximo permitido son 60 caracteres'},
			 solo_ad: {maxlength: 'El máximo permitido son 60 caracteres'},
			 p_adecuada: {required: 'Seleccione'},
			 todoadecuado: {required: 'Seleccione'},

			 accidentestrabajo: {required: 'Selecionar una opcion'},
			 empresaaccidente: {maxlength: 'El máximo permitido son 20 caracteres', texto: 'Ingrese solo texto'},
			 causaaccidente: {maxlength: 'El máximo permitido son 30 caracteres'},
			 parteafectadaaccidente: {maxlength: 'El máximo permitido son 30 caracteres'},
			 empresaaccidente2: {maxlength: 'El máximo permitido son 20 caracteres', texto: 'Ingrese solo texto'},
			 causaaccidente2: {maxlength: 'El máximo permitido son 30 caracteres'},
			 parteafectadaaccidente2: {maxlength: 'El máximo permitido son 30 caracteres'},
			 empresaaccidente3: {maxlength: 'El máximo permitido son 20 caracteres', texto: 'Ingrese solo texto'},
			 causaaccidente3: {maxlength: 'El máximo permitido son 30 caracteres'},
			 parteafectadaaccidente3: {maxlength: 'El máximo permitido son 30 caracteres'},
			 empresaaccidente4: {maxlength: 'El máximo permitido son 20 caracteres', texto: 'Ingrese solo texto'},
			 causaaccidente4: {maxlength: 'El máximo permitido son 30 caracteres'},
			 parteafectadaaccidente4: {maxlength: 'El máximo permitido son 30 caracteres'}, 
			 empresaaccidente5: {maxlength: 'El máximo permitido son 20 caracteres', texto: 'Ingrese solo texto'},
			 causaaccidente5: {maxlength: 'El máximo permitido son 30 caracteres'},
			 parteafectadaaccidente5: {maxlength: 'El máximo permitido son 30 caracteres'}, 

			 enfermedad_p: {required: 'Selecionar una opcion'},  
			 enfermedad:{maxlength: 'El máximo permitido son 60 caracteres'}, 
			 empresaenfermedad:{maxlength: 'El máximo permitido son 30 caracteres', texto: 'Ingrese solo texto'},
			 diagnosticoenfermedad: {maxlength: 'El máximo permitido son 150 caracteres'}, 

			 enfermedad2:{maxlength: 'El máximo permitido son 60 caracteres'}, 
			 empresaenfermedad2:{maxlength: 'El máximo permitido son 30 caracteres', texto: 'Ingrese solo texto'},
			 diagnosticoenfermedad2: {maxlength: 'El máximo permitido son 150 caracteres'},

			 enfermedad3:{maxlength: 'El máximo permitido son 60 caracteres'}, 
			 empresaenfermedad3:{maxlength: 'El máximo permitido son 30 caracteres', texto: 'Ingrese solo texto'},
			 diagnosticoenfermedad3: {maxlength: 'El máximo permitido son 150 caracteres'},

			 enfermedad4:{maxlength: 'El máximo permitido son 60 caracteres'}, 
			 empresaenfermedad4:{maxlength: 'El máximo permitido son 30 caracteres', texto: 'Ingrese solo texto'},
			 diagnosticoenfermedad4: {maxlength: 'El máximo permitido son 150 caracteres'},  

			 enfermedad5:{maxlength: 'El máximo permitido son 60 caracteres'}, 
			 empresaenfermedad5:{maxlength: 'El máximo permitido son 30 caracteres', texto: 'Ingrese solo texto'},
			 diagnosticoenfermedad5: {maxlength: 'El máximo permitido son 150 caracteres'},

			 deporte: {required: 'Selecionar una opcion'},
			 sedentario: {required: 'Selecionar una opcion'},
			 depor_cardiopulmonar: {required: 'Selecionar una opcion'},
			 cual_deporte: {maxlength: 'El máximo permitido son 60 caracteres'},

			 fuma: {required: 'Selecionar una opcion'},
			 fumador: {required: 'Selecionar una opcion'},
			 anosfumador: {digits: 'Sólo dígitos', minlength: 'El mínimo permitido son 1 caracteres', maxlength: 'El máximo permitido son 2 caracteres', min: 'Digite un año mayor o igual a 1', max:'Digite un año menor o igual a 99'},
			 exfumador: {required: 'Selecionar una opcion'},
			 anosexfumador: {digits: 'Sólo dígitos', minlength: 'El mínimo permitido son 1 caracteres', maxlength: 'El máximo permitido son 2 caracteres', min: 'Digite un año mayor o igual a 1', max:'Digite un año menor o igual a 99'},
			 cantidad_cigarrillos_dia: {digits: 'Sólo dígitos', minlength: 'El mínimo permitido son 1 caracteres', maxlength: 'El máximo permitido son 2 caracteres', min: 'Digite un año mayor o igual a 1', max:'Digite un  menor o igual a 70'},
			 tomahab: {required: 'Selecionar una opcion'},
			 anoshab_beber: {digits: 'Sólo dígitos', minlength: 'El mínimo permitido son 1 caracteres', maxlength: 'El máximo permitido son 2 caracteres', min: 'Digite un año mayor o igual a 1', max:'Digite un año menor o igual a 99'},
			 frec_beber: {required: 'Selecionar una opcion'},
			 problemasbebidas: {required: 'Selecionar una opcion'}, 
			 cuales_bebidas: {maxlength: 'El máximo permitido son 50 caracteres'},
			 exbebedor: {required: 'Selecionar una opcion'},
			 exbebedor_anos: {digits: 'Sólo dígitos', minlength: 'El mínimo permitido son 1 caracteres', maxlength: 'El máximo permitido son 2 caracteres', min: 'Digite un año mayor o igual a 1', max:'Digite un año menor o igual a 99'},
			 otroshabitos: {required: 'Selecionar una opcion'},
			 nombre_otrohabito: {maxlength: 'El máximo permitido son 50 caracteres'},
			 medic_regularmente: {required: 'Selecionar una opcion'},
			 nombre_medicamento: {maxlength: 'El máximo permitido son 50 caracteres'},
			 cirugiaseps: {required: 'Selecionar una opcion'},
			 cuales_cirugias: {maxlength: 'El máximo permitido son 50 caracteres'},
			 pend_tratamiento: {required: 'Selecionar una opcion'},
			 cuales_tratamientos: {maxlength: 'El máximo permitido son 50 caracteres'},
			 incapacidadultimosmeses: {required: 'Selecionar una opcion'},
			 motivo_incapacidad: {maxlength: 'El máximo permitido son 80 caracteres'}, 
			 mano_habil: {required: 'Selecionar una opcion'},
			 cicatrices: {required: 'Selecionar una opcion'},
			 tatuajes: {required: 'Selecionar una opcion'},
			 perimetro_abdominal: {required: 'Selecionar una opcion'},
			 perimetro_toraxico: {required: 'Selecionar una opcion'},
			 otras_mediciones: {maxlength: 'El máximo permitido son 120 caracteres'},
			 tensionarterial: {required: 'Este campo es requerido'},
			 frecuenciacardiaca: {required: 'Este campo es requerido'},
			 frecuenciarespiratoria: {required: 'Este campo es requerido'},
				talla: {required: 'Este campo es requerido'},
				peso: {required: 'Este campo es requerido'},
				pesodiagnostico: {required: 'Selecionar una opcion'},
				riesgos_suministrado: {required: 'Selecionar una opcion'},
				suministrado_otro: {maxlength: 'El máximo permitido son 50 caracteres'}
		 }

			});
		});
	});